# Generated by Django 4.2.30 on 2026-06-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('anomaly_type', models.CharField(choices=[('EXACT_DUPLICATE', 'Exact Duplicate'), ('CONFLICTING_DUPLICATE', 'Conflicting Duplicate'), ('AMOUNT_FORMAT', 'Amount Format Error'), ('NAME_FUZZY_MATCH', 'Name Fuzzy Match'), ('MISSING_PAID_BY', 'Missing Payer'), ('SETTLEMENT_PATTERN', 'Settlement Detected'), ('PERCENTAGE_SUM_ERROR', 'Percentage Sum ≠ 100%'), ('FOREIGN_CURRENCY', 'Foreign Currency Converted'), ('UNKNOWN_MEMBER', 'Unknown Member in Split'), ('NEGATIVE_AMOUNT', 'Negative Amount (Refund)'), ('NONSTANDARD_DATE', 'Non-standard Date Format'), ('MISSING_CURRENCY', 'Missing Currency'), ('ZERO_AMOUNT', 'Zero Amount'), ('AMBIGUOUS_DATE', 'Ambiguous Date Format'), ('MEMBER_POST_DEPARTURE', 'Member Included After Departure'), ('SPLIT_TYPE_CONFLICT', 'Split Type vs Details Conflict'), ('DECIMAL_PRECISION', 'Excessive Decimal Precision')], max_length=50)),
                ('description', models.TextField()),
                ('raw_row_data', models.JSONField()),
                ('suggested_fix', models.JSONField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('AUTO_FIXED', 'Auto Fixed — No Review Needed'), ('AUTO_IMPORTED', 'Imported Clean'), ('SKIPPED', 'Skipped'), ('PENDING_USER', 'Awaiting User Decision'), ('USER_RESOLVED', 'Resolved by User')], max_length=30)),
                ('requires_user_approval', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_choice', models.CharField(blank=True, max_length=50)),
                ('resolution_value', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_anomalies',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('pending_review', 'Pending User Review'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('auto_imported_count', models.IntegerField(default=0)),
                ('auto_fixed_count', models.IntegerField(default=0)),
                ('pending_review_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'db_table': 'import_sessions',
            },
        ),
    ]
